### PR TITLE
#6 Added sanitise function and modified transaction credit card

### PR DESCRIPTION
**Pull request by g-anupam**
Hey i have created a function to sanitise strings to remove special character. And i am trying to implement it in the transaction credit card page. Can you tell me if this is correct so that i can continue with other pages as well?

### CODE REVIEW

**Comment by anuragrao04** [comment]
yep, you're on the right path! tell me when you've finished making all commits to this PR

**Comment by g-anupam** [comment]
Yo i have sanitised all Transactions, item and selling page as mentioned in the issue #6.I have also fixed a minor syntax error.

**Comment by anuragrao04** [comment]
!bounty 40

**Comment by g-anupam** [comment]
hey can i apply the same function to the other sanitisation

**Comment by anuragrao04** [comment]
yes but there will be small differences with respect to context of the user input

**Comment by g-anupam** [comment]
ok will try as much as i can

**Pull request closed without merging**
